### ISSUE TITLE
gum choose does not and gum pager won't page

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/gumport#9] opened 2024-01-10 15:56 UTC
`gum choose` displays a list for selection but there is no way to move the cursor to select something.

`man zopen | gum pager` works but there is no way to scroll or find.

suspect both are related

this with the `gum` 13.0 level.

**Comment by lbdyck** [comment] 2024-01-10 16:15
This works:

`gum choose "A" "B" "C"`

But this fails:

`>man -k ssh | cut -d' ' -f1 | gum choose`

Both display a selection list but only the 1st allows scrolling and selection.

Surprisingly this works

`gum choose $(man -k ssh | cut -d' ' -f1)`

and this works for choose but not for pager

`gum pager $(gum choose $(man -k ssh | cut -d' ' -f1))`

**Comment by lbdyck** [comment] 2024-01-19 14:40
For the above issues replace `ssh` with `git` since there seem to be issues with `ssh` in man pages - the issues still exist however.

**Comment by lbdyck** [comment] 2024-01-24 15:43
@dustin-ward - I was told you are maintaining this port - anything I can do to provide more info on my issues?

**Comment by dustin-ward** [comment] 2024-01-24 15:53
Hello, sorry for the lack of updates. I am able to reproduce the issue, but I just haven't gotten around to diagnosing it yet. The issue seemingly only occurring with the pipe operator seems interesting to me. This is most likely an issue with our port of the bubble tea library used to build gum.

I'll let you know if I can find anything 👍

**Comment by lbdyck** [comment] 2024-01-24 15:54
@dustin-ward Thank you

**Comment by dustin-ward** [comment] 2024-01-24 17:41
I believe I have found the issue. It appears that when piping input into any gum tool, it receives keyboard input in EBCDIC instead of ascii.

Executing `echo "TEST" | gum write` will open up a text box that seemingly wont respond to input, but if I type the `` ` - or ESC`` keys we will see ``y ` and '`` respectively.

Dont have a fix for this at the moment, but that seems to be the issue if you can think of any temporary workarounds

**Comment by lbdyck** [comment] 2024-01-24 17:46
I have no words of wisdom or insight - once again we find character matters

**Closed as completed** 2024-01-25 20:49 UTC

**Comment by dustin-ward** [comment] 2024-01-25 20:50
@lbdyck Just merged the fix for this issue. Both of your test cases are working for me now, but feel free to let me know if you run into any other troubles :)

**Comment by lbdyck** [comment] 2024-01-25 21:37
once the `zopen upgrade` is available I'll test it.

btw. feel free to DM me on the System Z Enthusiast discord https://discord.gg/system-z-enthusiasts-880322471608344597

Thank you
